#ifndef QOPENGLFUNCTIONS_SELECTOR
#define QOPENGLFUNCTIONS_SELECTOR

#include <QOpenGLFunctions_3_3_Core>

#define QOPENGLFUNCTIONS_CLASSNAME QOpenGLFunctions_3_3_Core

#endif // QOPENGLFUNCTIONS_SELECTOR
